# install.packages("devtools")
#devtools::install_github("m-clark/gammit")
setwd("C:/Users/simon/OneDrive/Consulting/Taiwan/LW_share/analysis/")
library(plyr)
library(tidyverse)
library(lubridate)
library(lunar)
library(mgcv)
library(maps)
library(mapdata)
#library(maptools)
library(randomForest)
library(microbenchmark)
library(future)
library(future.callr)
library(mgcViz)
library(devtools)
#devtools::install_github("m-clark/gammit")
library(gammit)
library(boot)
library(cowplot)
library(magick)
library(fields)

plan(callr)
source("./support_functions.R")

